global using System;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using static System.Windows.Media.Colors;
global using static WpfCsMarkupExamples.Constants;
global using static WpfCsMarkupExamples.Styles;
global using UI = System.Windows;
global using ICommand = System.Windows.Input.ICommand;
global using Tweet = WpfCsMarkupExamples.SearchViewModel.Tweet;
global using BindingMode = System.Windows.Data.BindingMode;
global using Button_UI = System.Windows.Controls.Button;
global using TextBlock_UI = System.Windows.Controls.TextBlock;
global using TextBox_UI = System.Windows.Controls.TextBox;
global using InlineCollection_UI = System.Windows.Documents.InlineCollection;
global using ListViewItem_UI = System.Windows.Controls.ListViewItem;